version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: "123"
      MYSQL_DATABASE: spring
      MYSQL_ROOT_PASSWORD: "123"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_ALLOW_RUNAS: "true"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend-network

volumes:
  mysql-data:
  rabbitmq-data:

networks:
  backend-network:
    driver: bridge